apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dados
  labels:
    type: mysql-dados
spec: 
  storageClassName: manual
  capacity: 
    storage: 100Mi
  accessModes: 
    - ReadWriteOnce 
  hostPath: 
    path: /meubancoProjeto/